services:
  caddy:
    image: marktov/caddy:latest
    restart: always
    networks:
      - caddy-net-external
    ports:
      - "81:80"
      - "444:443"
      - "444:443/udp"
    environment:
      - ACME_EMAIL=$ACME_EMAIL
      - CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
      - ACME_AGREE=true
    volumes:
      - /mnt/portainer-compose-unpacker/stacks/ingress_external/homeserver_services/ingress/external/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data_ext:/data
      - caddy_config_ext:/config
    container_name: caddy_external
    
networks:
  caddy-net-external:
    driver: bridge
    attachable: true

volumes:
  caddy_data_ext:
    driver: local
  caddy_config_ext:
    driver: local
