services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    restart: always
    network:
      - caddy-net
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  uptime-kuma:
    driver_opts:
      type: local