services:
  postgresql:
    container_name: authentik-postgresql
    image: docker.io/library/postgres:12-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
  redis:
    container_name: authentik-redis
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
  server:
    container_name: authentik-server
    image: ghcr.io/goauthentik/server:latest
    restart: always
    command: server
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - authentik_media:/media
      - authentik_templates:/templates
    ports:
      - "9000:9000"
      - "9444:9443"
    depends_on:
      - postgresql
      - redis
  worker:
    container_name: authentik-worker
    image: ghcr.io/goauthentik/server:latest
    restart: always
    command: worker
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik_media:/media
      - authentik_certs:/certs
      - authentik_templates:/templates
    depends_on:
      - postgresql
      - redis
volumes:
  database:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/pve/docker/data/authentik/database"
  redis:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/pve/docker/data/authentik/redis"
  authentik_media:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/pve/docker/data/authentik/media"
  authentik_certs:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/pve/docker/data/authentik/certs"
  authentik_templates:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/pve/docker/data/authentik/templates"
