services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: always
    network_mode: host
volumes:
  homeassistant:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/pve/docker/data/homeassistant"
