services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx-proxy-manager-data:/data
      - nginx-proxy-manager-letsencrypt:/etc/letsencrypt
volumes:
  nginx-proxy-manager-data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/storagepool/docker/nginx-proxy-manager/data"
  nginx-proxy-manager-letsencrypt:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/storagepool/docker/nginx-proxy-manager/letsencrypt"
