services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma:/app/data
volumes:
  uptime-kuma:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.101,nolock,soft,rw"
      device: ":/docker/uptime-kuma"