services:
  emby:
    image: emby/embyserver:beta
    container_name: emby
    network_mode: host
    environment:
      - UID=65534
      - GID=65534
      - GIDLIST=44,109
    volumes:
      - emby:/config
      - media:/mnt/media
    networks:
      - caddy-net-internal
    devices:
      - "/dev/dri:/dev/dri"
    restart: always
volumes:
  emby:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/pve/docker/data/emby"