services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000
      - GID=1000
      - GIDLIST=100
    volumes:
      - /path/to/programdata:/config # Configuration directory
      - media:/mnt/media
    ports:
      - 8096:8096
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    restart: always
volumes:
	emby: