services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=America/Toronto
    ports:
      - 5055:5055
    volumes:
      - jellyseerr:/app/config
    restart: unless-stopped
volumes:
  jellyseerr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/storagepool/docker/jellyseerr"
