services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - media:/media
    restart: always
volumes:
  jellyfin-config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/storagepool/docker/jellyfin/config"
  jellyfin-cache:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/storagepool/docker/jellyfin/cache"
