services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=America/Toronto
    ports:
      - 5055:5055
    volumes:
      - overseerr:/app/config
    restart: unless-stopped
volumes:
  overseerr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/pve/docker/data/overseerr"
