services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    volumes:
      - plex-config:/config
      - media:/media
    restart: always
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
volumes:
  plex-config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/pve/docker/data/plex"
