services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    volumes:
      - plex-config:/config
      - media:/media
    restart: always
    devices:
      - "/dev/dri:/dev/dri"
volumes:
  plex-config:
    driver: local
