services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: always
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Toronto
    volumes:
      - prowlarr:/config
volumes:
  prowlarr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/pve/docker/data/prowlarr"
