services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    restart: always
    networks:
      - caddy-net-internal
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Toronto
    volumes:
      - radarr:/config
      - media:/data
volumes:
  radarr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/pve/docker/data/radarr"
