services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Toronto
    volumes:
      - sonarr:/config
      - media:/data
volumes:
  sonarr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/storagepool/docker/sonarr"
