services:
  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - media:/data
      - transmission-openvpn:/config
    environment:
      - OPENVPN_PROVIDER=WINDSCRIBE
      - OPENVPN_CONFIG=Toronto-ComfortZone-tcp
      - OPENVPN_USERNAME=$OPENVPN_USERNAME
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - LOCAL_NETWORK=192.168.2.0/24
      - TRANSMISSION_DOWNLOAD_DIR=/data/downloads
      - TRANSMISSION_INCOMPLETE_DIR=
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - caddy-net-internal
    devices:
      - /dev/net/tun
volumes:
  transmission-openvpn:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.100,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/pve/docker/data/transmission-openvpn"
