services:
  caddy:
    image: marktov/caddy:latest
    restart: always
    networks:
      - caddy-net-internal
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - ACME_EMAIL=$ACME_EMAIL
      - CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
      - ACME_AGREE=true
    volumes:
      - /mnt/portainer-compose-unpacker/stacks/ingress_internal/homeserver_services/ingress/internal/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    container_name: caddy
    
networks:
  caddy-net-internal:
    driver: bridge
    attachable: true
    external: true

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
